name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout dos arquivos
      uses: actions/checkout@v3
    - name: Rodar scripts
      run: |
        echo 'Live no Microsoft Reactor'
        dotnet --list-sdks
        cat 'README.md'

  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Rodar scripts
      run: |
        echo 'Mais um teste durante live no Microsoft Reactor'
        dotnet --list-sdks
        cat 'README.md'
    - name: Segundo step
      run: echo 'Segundo setp'
