name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout dos arquivos
      uses: actions/checkout@v3
    - name: Rodar scripts
      run: echo 'Live no Microsoft Reactor'
